spring:
  profiles: dev
  # Add any development-specific configurations here
  server:
    port: 8080  # Example: set the server port
  logging:
    level:
      root: DEBUG  # Example: set the logging level to DEBUG for development
