spring:
  profiles: prod
  # Add any production-specific configurations here
  server:
    port: 80  # Example: set the server port
  logging:
    level:
      root: INFO  # Example: set the logging level to INFO for production
